CREATE SCHEMA raw;

ALTER TABLE stories SET SCHEMA raw;
ALTER TABLE jobs SET SCHEMA raw;
ALTER TABLE comments SET SCHEMA raw;
ALTER TABLE polls SET SCHEMA raw;
ALTER TABLE pollopts SET SCHEMA raw;
ALTER TABLE parents SET SCHEMA raw;
ALTER TABLE deleted SET SCHEMA raw;
ALTER TABLE dead SET SCHEMA raw;
ALTER TABLE skipped SET SCHEMA raw;
ALTER TABLE scrape SET SCHEMA raw;